# Generated by Django 6.0.3 on 2026-03-24 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossarioTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('termo_correto', models.CharField(max_length=200, verbose_name='Termo correto')),
                ('variantes', models.JSONField(default=list, help_text='Lista de variações fonéticas ou escritas incorretas. Ex: ["urdidúra", "urdidura"]', verbose_name='Variantes fonéticas')),
                ('categoria', models.CharField(choices=[('tecelagem', 'Tecelagem'), ('urdimento', 'Urdimento'), ('acabamento', 'Acabamento'), ('malharia', 'Malharia'), ('tinturaria', 'Tinturaria'), ('manutencao', 'Manutenção'), ('qualidade', 'Qualidade'), ('gestao', 'Gestão'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/contexto')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Termo do Glossário',
                'verbose_name_plural': 'Termos do Glossário',
                'ordering': ['categoria', 'termo_correto'],
            },
        ),
        migrations.CreateModel(
            name='OneDriveToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onedrive_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token OneDrive',
                'verbose_name_plural': 'Tokens OneDrive',
            },
        ),
        migrations.CreateModel(
            name='TranscricaoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onedrive_file_id', models.CharField(max_length=500, verbose_name='ID do arquivo no OneDrive')),
                ('onedrive_file_name', models.CharField(max_length=500, verbose_name='Nome do arquivo')),
                ('onedrive_folder_path', models.CharField(max_length=1000, verbose_name='Pasta de origem')),
                ('status', models.CharField(choices=[('pending', 'Aguardando'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falha')], db_index=True, default='pending', max_length=20)),
                ('transcricao_raw', models.TextField(blank=True, verbose_name='Transcrição bruta (Whisper)')),
                ('transcricao_processada', models.TextField(blank=True, verbose_name='Transcrição com glossário aplicado')),
                ('erro', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('duracao_segundos', models.IntegerField(blank=True, null=True, verbose_name='Duração do áudio (s)')),
                ('tokens_usados', models.IntegerField(blank=True, null=True, verbose_name='Tokens OpenAI usados')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcricao_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job de Transcrição',
                'verbose_name_plural': 'Jobs de Transcrição',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=300, verbose_name='Título da reunião')),
                ('data_reuniao', models.DateField(verbose_name='Data da reunião')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('participantes', models.TextField(blank=True, verbose_name='Participantes')),
                ('pauta', models.TextField(blank=True, verbose_name='Pauta')),
                ('deliberacoes', models.TextField(blank=True, verbose_name='Deliberações')),
                ('acoes', models.JSONField(default=list, help_text='Lista de {acao, responsavel, prazo}', verbose_name='Ações')),
                ('conteudo_completo', models.TextField(blank=True, verbose_name='Ata completa formatada')),
                ('onedrive_docx_id', models.CharField(blank=True, max_length=500, verbose_name='ID do .docx no OneDrive')),
                ('onedrive_docx_path', models.CharField(blank=True, max_length=1000, verbose_name='Caminho do .docx')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ata', to='transcricao.transcricaojob')),
            ],
            options={
                'verbose_name': 'Ata',
                'verbose_name_plural': 'Atas',
                'ordering': ['-data_reuniao'],
            },
        ),
    ]
