# Generated by Django 4.2.9 on 2026-03-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcricao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcricaojob',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/', verbose_name='Arquivo de áudio (upload)'),
        ),
        migrations.AddField(
            model_name='transcricaojob',
            name='origem',
            field=models.CharField(choices=[('upload', 'Upload direto'), ('onedrive', 'OneDrive')], default='upload', max_length=20),
        ),
        migrations.AlterField(
            model_name='transcricaojob',
            name='onedrive_file_id',
            field=models.CharField(blank=True, max_length=500, verbose_name='ID do arquivo no OneDrive'),
        ),
        migrations.AlterField(
            model_name='transcricaojob',
            name='onedrive_file_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nome do arquivo'),
        ),
        migrations.AlterField(
            model_name='transcricaojob',
            name='onedrive_folder_path',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Pasta de origem'),
        ),
    ]
