# Generated by Django 4.2.9 on 2025-04-25 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carona', '0002_pessoa_alter_veiculo_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
