# Generated by Django 4.2.9 on 2025-04-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carona', '0005_alter_carona_id_alter_participante_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participante',
            options={'ordering': ['carona', 'pessoa'], 'verbose_name': 'Participante de Carona', 'verbose_name_plural': 'Participantes de Carona'},
        ),
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='participante',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carona_participantes', to='carona.pessoa', verbose_name='Participante'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together={('carona', 'pessoa')},
        ),
        migrations.RemoveField(
            model_name='participante',
            name='user',
        ),
    ]
